export const ROUTES_BY_ROLE = {
  admin: [
    "dashboard",
    "sector-master",
    "office-master",
    "geo-location",
    "department-master",
    "designation-master",
    "employee-master",
    "office-allocation",
    "shift-master",
    "leave-type",
    "weekend-master",
    "attendance-request",
    "leave-request",
    "shift",
    "shift-assignment",
    "shift-override",
    "reports",
    "day-wise-report",
    "employee-wise-report",
    "leave-report",
    "device-info",
  ],
  user: ["dashboard"],
};
